In [1]:
""" DATA PREPROCESSING """

' DATA PREPROCESSING '

In [2]:
import os
import pandas as pd
import numpy as np

In [3]:
DATAFRAMES_PATH = '../DATAS/'
SEASONS = range(2018,2024)

In [4]:
#Load all excel and join in one dataframe
def load_dataframes():
    full_dataframe = pd.DataFrame(dtype=float)
    for season in SEASONS:
        df = pd.read_excel(DATAFRAMES_PATH+f'season_{season}.xlsx')
        df["SEASON"] = season
        full_dataframe = pd.concat([full_dataframe, df], ignore_index=True)
        
    print("Datas imported successfully !")
    return full_dataframe

In [5]:
DATAFRAME = load_dataframes()

Datas imported successfully !

In [6]:
#Charlotte Bobcats got renamed Charlotte Hornets in 2014-2015 so i have to change CHO to CHA
DATAFRAME['TEAM'].value_counts()

TEAM
BOS    282
MIA    273
MIL    273
GSW    270
DEN    269
PHI    268
TOR    260
UTA    258
LAC    258
LAL    256
PHO    256
HOU    254
DAL    254
POR    254
ATL    251
MEM    250
BRK    250
OKC    247
IND    246
SAS    246
NOP    245
ORL    244
CLE    243
WAS    242
MIN    242
NYK    241
SAC    240
CHI    236
CHO    236
DET    235
Name: count, dtype: int64

In [7]:
DATAFRAME['TEAM'] = DATAFRAME['TEAM'].replace("CHO", "CHA")
len(DATAFRAME['TEAM'].value_counts())

30

In [8]:
del DATAFRAME["MP"]
del DATAFRAME["OPP_MP"]

In [9]:
DATAFRAME

,3P,3P%,3PA,AST,BLK,DRB,FG,FG%,FGA,FT,...,OPP_MP_MAX,OPP_PF_MAX,OPP_PTS_MAX,OPP_STL_MAX,OPP_TOV_MAX,OPP_TRB_MAX,TEAM,TEAM_OPP,WON,SEASON
0,8,0.250,32,24,4,37,36,0.409,88,19,...,3,4,29,2,4,16,BOS,CLE,True,2018
1,15,0.366,41,28,5,33,47,0.485,97,13,...,1,4,23,2,8,11,HOU,GSW,True,2018
2,7,0.333,21,19,4,39,38,0.500,76,25,...,3,6,18,3,3,9,MIL,BOS,False,2018
3,9,0.500,18,20,6,36,48,0.511,94,12,...,2,4,16,1,5,11,ATL,DAL,True,2018
4,9,0.300,30,16,3,44,29,0.397,73,23,...,5,4,27,4,3,13,CHA,DET,False,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7574,13,0.333,39,26,4,32,39,0.406,96,2,...,2,2,27,1,3,13,MIA,DEN,True,2023
7575,17,0.486,35,28,4,23,38,0.487,78,18,...,3,6,41,3,5,11,MIA,DEN,True,2023
7576,5,0.278,18,28,5,45,41,0.513,80,22,...,6,4,28,2,2,17,DEN,MIA,False,2023
7577,14,0.500,28,26,7,29,39,0.494,79,16,...,2,4,25,1,7,11,DEN,MIA,True,2023
7578,9,0.257,35,18,7,33,33,0.344,96,14,...,4,4,28,2,6,16,MIA,DEN,True,2023

In [10]:
#Add the target value 
def add_target(team):
    team["TARGET"] = team["WON"].shift(-1)
    return team

df = DATAFRAME.groupby("TEAM", group_keys=False).apply(add_target)

In [11]:
df[df["TEAM"] == "MEM"]

,3P,3P%,3PA,AST,BLK,DRB,FG,FG%,FGA,FT,...,OPP_PF_MAX,OPP_PTS_MAX,OPP_STL_MAX,OPP_TOV_MAX,OPP_TRB_MAX,TEAM,TEAM_OPP,WON,SEASON,TARGET
43,6,0.316,19,16,2,35,29,0.426,68,34,...,5,27,1,7,8,MEM,HOU,False,2018,False
56,12,0.387,31,14,2,30,33,0.458,72,16,...,5,19,2,3,6,MEM,DAL,False,2018,True
133,13,0.419,31,21,7,30,40,0.476,84,20,...,4,30,2,5,11,MEM,LAC,True,2018,True
138,11,0.297,37,23,7,33,40,0.460,87,11,...,4,21,2,4,12,MEM,LAL,True,2018,False
152,7,0.368,19,18,10,29,35,0.479,73,21,...,4,36,3,5,10,MEM,POR,False,2018,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7467,20,0.476,42,39,6,33,53,0.570,93,11,...,4,25,2,5,8,MEM,MIL,True,2023,True
7484,7,0.189,37,25,4,32,40,0.435,92,13,...,6,25,2,5,15,MEM,OKC,True,2023,True
7519,13,0.333,39,23,2,32,35,0.376,93,18,...,5,31,2,3,17,MEM,LAL,True,2023,True
7525,9,0.214,42,26,7,33,42,0.396,106,18,...,6,23,2,4,20,MEM,LAL,True,2023,True
7536,12,0.316,38,19,2,31,29,0.302,96,15,...,4,31,2,3,14,MEM,LAL,True,2023,NaN

In [12]:
df[df["TEAM"] == "MEM"]

,3P,3P%,3PA,AST,BLK,DRB,FG,FG%,FGA,FT,...,OPP_PF_MAX,OPP_PTS_MAX,OPP_STL_MAX,OPP_TOV_MAX,OPP_TRB_MAX,TEAM,TEAM_OPP,WON,SEASON,TARGET
43,6,0.316,19,16,2,35,29,0.426,68,34,...,5,27,1,7,8,MEM,HOU,False,2018,False
56,12,0.387,31,14,2,30,33,0.458,72,16,...,5,19,2,3,6,MEM,DAL,False,2018,True
133,13,0.419,31,21,7,30,40,0.476,84,20,...,4,30,2,5,11,MEM,LAC,True,2018,True
138,11,0.297,37,23,7,33,40,0.460,87,11,...,4,21,2,4,12,MEM,LAL,True,2018,False
152,7,0.368,19,18,10,29,35,0.479,73,21,...,4,36,3,5,10,MEM,POR,False,2018,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7467,20,0.476,42,39,6,33,53,0.570,93,11,...,4,25,2,5,8,MEM,MIL,True,2023,True
7484,7,0.189,37,25,4,32,40,0.435,92,13,...,6,25,2,5,15,MEM,OKC,True,2023,True
7519,13,0.333,39,23,2,32,35,0.376,93,18,...,5,31,2,3,17,MEM,LAL,True,2023,True
7525,9,0.214,42,26,7,33,42,0.396,106,18,...,6,23,2,4,20,MEM,LAL,True,2023,True
7536,12,0.316,38,19,2,31,29,0.302,96,15,...,4,31,2,3,14,MEM,LAL,True,2023,NaN

In [13]:
df["TARGET"][pd.isnull(df["TARGET"])] = 2

C:\Users\lsaid\AppData\Local\Temp\ipykernel_25180\1660968851.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["TARGET"][pd.isnull(df["TARGET"])] = 2

In [14]:
df["TARGET"] = df["TARGET"].astype(int, errors="ignore")

In [15]:
df[df["TEAM"] == "MEM"]

,3P,3P%,3PA,AST,BLK,DRB,FG,FG%,FGA,FT,...,OPP_PF_MAX,OPP_PTS_MAX,OPP_STL_MAX,OPP_TOV_MAX,OPP_TRB_MAX,TEAM,TEAM_OPP,WON,SEASON,TARGET
43,6,0.316,19,16,2,35,29,0.426,68,34,...,5,27,1,7,8,MEM,HOU,False,2018,0
56,12,0.387,31,14,2,30,33,0.458,72,16,...,5,19,2,3,6,MEM,DAL,False,2018,1
133,13,0.419,31,21,7,30,40,0.476,84,20,...,4,30,2,5,11,MEM,LAC,True,2018,1
138,11,0.297,37,23,7,33,40,0.460,87,11,...,4,21,2,4,12,MEM,LAL,True,2018,0
152,7,0.368,19,18,10,29,35,0.479,73,21,...,4,36,3,5,10,MEM,POR,False,2018,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7467,20,0.476,42,39,6,33,53,0.570,93,11,...,4,25,2,5,8,MEM,MIL,True,2023,1
7484,7,0.189,37,25,4,32,40,0.435,92,13,...,6,25,2,5,15,MEM,OKC,True,2023,1
7519,13,0.333,39,23,2,32,35,0.376,93,18,...,5,31,2,3,17,MEM,LAL,True,2023,1
7525,9,0.214,42,26,7,33,42,0.396,106,18,...,6,23,2,4,20,MEM,LAL,True,2023,1
7536,12,0.316,38,19,2,31,29,0.302,96,15,...,4,31,2,3,14,MEM,LAL,True,2023,2

In [16]:
#Scaling datas
unscalable_column = ["WON", "TARGET", "TEAM", "TEAM_OPP", "SEASON"]
scalable_column = df.columns[~df.columns.isin(unscalable_column)]

In [17]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled_scores = scaler.fit_transform([df["PTS"]])
df[scalable_column] = scaler.fit_transform(df[scalable_column]) #Scaling datas between 0 and 1 to improve ML Model Performance

In [18]:
""" MACHINE LEARNING """

' MACHINE LEARNING '

In [19]:
from sklearn.model_selection import TimeSeriesSplit #CANT USE BASIC CROSS VALIDATION SPLIT BC CASE WHERE THE FUTURES OBS ARE TRAINED TO PREDICT THE PAST
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

rr = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=5)
sfs = SequentialFeatureSelector(rr, n_features_to_select=20 ,direction="backward", cv=split)

In [20]:
sfs.fit(df[scalable_column], df["TARGET"]) #Find what features make prediction better

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None),
                          direction='backward',
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=20)

In [21]:
predictors = list(scalable_column[sfs.get_support()])

In [22]:
predictors

['3PA',
 'FG',
 'FG%',
 'FT',
 'FTA',
 'PF',
 'OPP_3P%',
 'OPP_3PA',
 'OPP_AST',
 'OPP_DRB',
 'OPP_FG%',
 'OPP_TOV',
 '3PA_MAX',
 'FT_MAX',
 'FTA_MAX',
 'STL_MAX',
 'TOV_MAX',
 'OPP_3PA_MAX',
 'OPP_FG_MAX',
 'OPP_PTS_MAX']

In [23]:
def backtest(data, model, predictors, start=2, step=1):
    all_predictions = []
    seasons = sorted(df["SEASON"].unique())
    
    for i in range(start, len(seasons), step):
        season = seasons[i]
        
        train = data[data["SEASON"] < season] #Get All Datas before current season
        test = data[data["SEASON"] == season]
        
        model.fit(train[predictors], train["TARGET"])
        preds = model.predict(test[predictors])
        
        preds = pd.Series(preds, index=test.index) #Change np.array to df for next step
        
        combined = pd.concat([test["TARGET"], preds], axis=1) #Df who shows actual value and the predicted one
        combined.columns = ["ACTUAL", "PREDICTION"]
        
        all_predictions.append(combined)
    
    return pd.concat(all_predictions)

In [24]:
predictions = backtest(df, rr, predictors)

In [25]:
predictions

      ACTUAL  PREDICTION
2624       0           0
2625       1           0
2626       1           0
2627       0           0
2628       1           0
...      ...         ...
7574       1           1
7575       1           0
7576       1           0
7577       2           1
7578       2           0

[4955 rows x 2 columns]

In [26]:
from sklearn.metrics import accuracy_score

predictions = predictions[predictions["ACTUAL"] != 2]
accuracy_score(predictions["ACTUAL"], predictions["PREDICTION"])

0.5557360406091371

In [ ]:
""" AS YOU WILL SEE, THE PERFORMANCE IMPROVING WAS UNSUCCESSFUL. THEREFORE, I WILL EXPORT MY ML MODEL """

In [28]:
import pickle
pickle.dump(rr, open("nba-result-ml.sav", "wb"))

In [27]:
df["WON"][df["PTS"] > 0.5].value_counts()

WON
False    822
True     768
Name: count, dtype: int64

In [28]:
""" PERFORMANCE IMPROVING (NOT REALLY ACTUALLY)"""

' PERFORMANCE IMPROVING '

In [29]:
df_rolling = df[list(scalable_column) + ["WON", "TEAM", "SEASON"]]
df_rolling

,3P,3P%,3PA,AST,BLK,DRB,FG,FG%,FGA,FT,...,OPP_FTA_MAX,OPP_MP_MAX,OPP_PF_MAX,OPP_PTS_MAX,OPP_STL_MAX,OPP_TOV_MAX,OPP_TRB_MAX,WON,TEAM,SEASON
0,0.310345,0.605364,0.254237,0.268293,0.315789,0.291667,0.340909,0.280576,0.470588,0.098039,...,0.181818,0.400000,0.75,0.253968,0.222222,0.363636,0.461538,True,ORL,2014
1,0.275862,0.486590,0.288136,0.512195,0.210526,0.375000,0.454545,0.537170,0.323529,0.235294,...,0.212121,0.466667,0.75,0.222222,0.111111,0.363636,0.346154,False,LAC,2014
2,0.241379,0.343550,0.372881,0.414634,0.210526,0.375000,0.318182,0.364508,0.323529,0.333333,...,0.242424,0.133333,0.50,0.142857,0.555556,0.181818,0.153846,True,CHI,2014
3,0.310345,0.478927,0.338983,0.439024,0.421053,0.333333,0.272727,0.316547,0.308824,0.352941,...,0.242424,0.200000,0.50,0.158730,0.333333,0.090909,0.192308,False,BRK,2014
4,0.275862,0.425287,0.338983,0.512195,0.263158,0.333333,0.363636,0.520384,0.220588,0.509804,...,0.212121,0.333333,0.50,0.380952,0.222222,0.545455,0.192308,False,ATL,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12829,0.448276,0.425287,0.593220,0.487805,0.210526,0.416667,0.409091,0.326139,0.514706,0.019608,...,0.333333,0.133333,0.00,0.301587,0.111111,0.181818,0.346154,True,MIA,2023
12830,0.586207,0.620690,0.525424,0.536585,0.210526,0.229167,0.386364,0.520384,0.250000,0.333333,...,0.212121,0.200000,1.00,0.523810,0.333333,0.363636,0.269231,True,MIA,2023
12831,0.172414,0.355045,0.237288,0.536585,0.263158,0.687500,0.454545,0.582734,0.279412,0.411765,...,0.272727,0.400000,0.50,0.317460,0.222222,0.090909,0.500000,False,DEN,2023
12832,0.482759,0.638570,0.406780,0.487805,0.368421,0.354167,0.409091,0.537170,0.264706,0.294118,...,0.242424,0.133333,0.50,0.269841,0.111111,0.545455,0.269231,True,DEN,2023
12833,0.310345,0.328225,0.525424,0.292683,0.368421,0.437500,0.272727,0.177458,0.514706,0.254902,...,0.151515,0.266667,0.50,0.317460,0.222222,0.454545,0.461538,True,MIA,2023

In [30]:
def find_team_averages(team): #Get the mean performance of a team for the last 10 games
    numeric_columns = team.select_dtypes(include='number').columns
    rolling = team
    rolling[numeric_columns] = team[numeric_columns].rolling(10).mean()

    return rolling

df_rolling = df_rolling.groupby(["TEAM", "SEASON"], group_keys=False).apply(find_team_averages)

In [31]:
df_rolling

,3P,3P%,3PA,AST,BLK,DRB,FG,FG%,FGA,FT,...,OPP_FTA_MAX,OPP_MP_MAX,OPP_PF_MAX,OPP_PTS_MAX,OPP_STL_MAX,OPP_TOV_MAX,OPP_TRB_MAX,WON,TEAM,SEASON
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,ORL,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,LAC,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,CHI,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BRK,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,ATL,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12829,0.472414,0.496807,0.540678,0.446341,0.178947,0.381250,0.465909,0.476499,0.410294,0.227451,...,0.275758,0.253333,0.550,0.334921,0.211111,0.345455,0.342308,True,MIA,2023.0
12830,0.475862,0.502171,0.538983,0.451220,0.189474,0.358333,0.450000,0.464748,0.401471,0.231373,...,0.290909,0.253333,0.575,0.360317,0.222222,0.363636,0.326923,True,MIA,2023.0
12831,0.368966,0.446360,0.444068,0.514634,0.236842,0.450000,0.518182,0.560192,0.386765,0.329412,...,0.287879,0.246667,0.725,0.407937,0.233333,0.209091,0.300000,False,DEN,2023.0
12832,0.389655,0.465773,0.452542,0.519512,0.263158,0.450000,0.506818,0.551559,0.380882,0.323529,...,0.290909,0.246667,0.725,0.401587,0.222222,0.236364,0.315385,True,DEN,2023.0
12833,0.448276,0.486718,0.522034,0.434146,0.200000,0.352083,0.411364,0.438129,0.380882,0.237255,...,0.239394,0.253333,0.550,0.344444,0.233333,0.354545,0.311538,True,MIA,2023.0

In [32]:
rolling_cols = [f"{col}_10" for col in df_rolling.columns]
df_rolling.columns = rolling_cols
df = pd.concat([df, df_rolling], axis=1)

In [33]:
df

,3P,3P%,3PA,AST,BLK,DRB,FG,FG%,FGA,FT,...,OPP_FTA_MAX_10,OPP_MP_MAX_10,OPP_PF_MAX_10,OPP_PTS_MAX_10,OPP_STL_MAX_10,OPP_TOV_MAX_10,OPP_TRB_MAX_10,WON_10,TEAM_10,SEASON_10
0,0.310345,0.605364,0.254237,0.268293,0.315789,0.291667,0.340909,0.280576,0.470588,0.098039,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,ORL,NaN
1,0.275862,0.486590,0.288136,0.512195,0.210526,0.375000,0.454545,0.537170,0.323529,0.235294,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,LAC,NaN
2,0.241379,0.343550,0.372881,0.414634,0.210526,0.375000,0.318182,0.364508,0.323529,0.333333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,CHI,NaN
3,0.310345,0.478927,0.338983,0.439024,0.421053,0.333333,0.272727,0.316547,0.308824,0.352941,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,BRK,NaN
4,0.275862,0.425287,0.338983,0.512195,0.263158,0.333333,0.363636,0.520384,0.220588,0.509804,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,ATL,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12829,0.448276,0.425287,0.593220,0.487805,0.210526,0.416667,0.409091,0.326139,0.514706,0.019608,...,0.275758,0.253333,0.550,0.334921,0.211111,0.345455,0.342308,True,MIA,2023.0
12830,0.586207,0.620690,0.525424,0.536585,0.210526,0.229167,0.386364,0.520384,0.250000,0.333333,...,0.290909,0.253333,0.575,0.360317,0.222222,0.363636,0.326923,True,MIA,2023.0
12831,0.172414,0.355045,0.237288,0.536585,0.263158,0.687500,0.454545,0.582734,0.279412,0.411765,...,0.287879,0.246667,0.725,0.407937,0.233333,0.209091,0.300000,False,DEN,2023.0
12832,0.482759,0.638570,0.406780,0.487805,0.368421,0.354167,0.409091,0.537170,0.264706,0.294118,...,0.290909,0.246667,0.725,0.401587,0.222222,0.236364,0.315385,True,DEN,2023.0
12833,0.310345,0.328225,0.525424,0.292683,0.368421,0.437500,0.272727,0.177458,0.514706,0.254902,...,0.239394,0.253333,0.550,0.344444,0.233333,0.354545,0.311538,True,MIA,2023.0

In [35]:
df = df.dropna()
df.columns

Index(['3P', '3P%', '3PA', 'AST', 'BLK', 'DRB', 'FG', 'FG%', 'FGA', 'FT',
       ...
       'OPP_FTA_MAX_10', 'OPP_MP_MAX_10', 'OPP_PF_MAX_10', 'OPP_PTS_MAX_10',
       'OPP_STL_MAX_10', 'OPP_TOV_MAX_10', 'OPP_TRB_MAX_10', 'WON_10',
       'TEAM_10', 'SEASON_10'],
      dtype='object', length=152)

In [38]:
del df["WON_10"]
del df["TEAM_10"]
del df["SEASON_10"]

In [39]:
df

,3P,3P%,3PA,AST,BLK,DRB,FG,FG%,FGA,FT,...,OPP_FGA_MAX_10,OPP_FT_MAX_10,OPP_FT%_MAX_10,OPP_FTA_MAX_10,OPP_MP_MAX_10,OPP_PF_MAX_10,OPP_PTS_MAX_10,OPP_STL_MAX_10,OPP_TOV_MAX_10,OPP_TRB_MAX_10
201,0.310345,0.574713,0.271186,0.390244,0.263158,0.333333,0.318182,0.402878,0.279412,0.313725,...,0.163415,0.208,0.981259,0.206061,0.293333,0.425,0.204762,0.333333,0.400000,0.234615
228,0.137931,0.283525,0.237288,0.170732,0.105263,0.375000,0.250000,0.244604,0.367647,0.333333,...,0.209756,0.220,1.000000,0.212121,0.240000,0.625,0.253968,0.277778,0.254545,0.226923
232,0.206897,0.348659,0.305085,0.439024,0.157895,0.354167,0.363636,0.350120,0.411765,0.274510,...,0.178049,0.224,0.970015,0.196970,0.260000,0.625,0.246032,0.288889,0.281818,0.265385
233,0.206897,0.425287,0.237288,0.243902,0.526316,0.395833,0.181818,0.304556,0.176471,0.156863,...,0.212195,0.188,0.970015,0.175758,0.280000,0.525,0.238095,0.255556,0.372727,0.284615
234,0.275862,0.393359,0.372881,0.341463,0.315789,0.562500,0.477273,0.412470,0.500000,0.372549,...,0.241463,0.232,0.970015,0.236364,0.320000,0.675,0.261905,0.366667,0.318182,0.276923
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12829,0.448276,0.425287,0.593220,0.487805,0.210526,0.416667,0.409091,0.326139,0.514706,0.019608,...,0.309756,0.264,0.974963,0.275758,0.253333,0.550,0.334921,0.211111,0.345455,0.342308
12830,0.586207,0.620690,0.525424,0.536585,0.210526,0.229167,0.386364,0.520384,0.250000,0.333333,...,0.331707,0.284,0.974963,0.290909,0.253333,0.575,0.360317,0.222222,0.363636,0.326923
12831,0.172414,0.355045,0.237288,0.536585,0.263158,0.687500,0.454545,0.582734,0.279412,0.411765,...,0.339024,0.324,0.974963,0.287879,0.246667,0.725,0.407937,0.233333,0.209091,0.300000
12832,0.482759,0.638570,0.406780,0.487805,0.368421,0.354167,0.409091,0.537170,0.264706,0.294118,...,0.341463,0.316,0.974963,0.290909,0.246667,0.725,0.401587,0.222222,0.236364,0.315385
12833,0.310345,0.328225,0.525424,0.292683,0.368421,0.437500,0.272727,0.177458,0.514706,0.254902,...,0.307317,0.256,0.974963,0.239394,0.253333,0.550,0.344444,0.233333,0.354545,0.311538

In [43]:
df["TARGET"]

201      1
228      1
232      0
233      1
234      1
        ..
12829    1
12830    1
12831    1
12832    2
12833    2
Name: TARGET, Length: 10134, dtype: int32

In [44]:
sfs.fit(df[scalable_column], df["TARGET"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=20)

In [74]:
predictors = list(scalable_column[sfs.get_support()])
predictors

['3P%',
 'AST',
 'DRB',
 'ORB',
 'TOV',
 'TRB',
 'OPP_FGA',
 'OPP_ORB',
 '3P%_MAX',
 'AST_MAX',
 'BLK_MAX',
 'FT_MAX',
 'TOV_MAX',
 'TRB_MAX',
 'OPP_3PA_MAX',
 'OPP_FGA_MAX',
 'OPP_FT%_MAX',
 'OPP_MP_MAX',
 'OPP_PTS_MAX',
 'OPP_TRB_MAX']

In [75]:
new_predictions = backtest(df, rr, predictors)

In [76]:
new_predictions = new_predictions[new_predictions["ACTUAL"] != 2]
accuracy_score(new_predictions["ACTUAL"], new_predictions["PREDICTION"])

0.5280758672323435

In [ ]:
""" As we can see, adding those new values made the predictions less efficient. """